version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - ps: >-
      $MVNDIR = 'C:\tools\apache-maven-3.6.0\'

      if(!(Test-Path -Path $MVNDIR )){
        Write-Host (Test-Path -Path $MVNDIR)
        Write-Host 'Installing Maven'
        cinst maven -Version 3.6.0
      } else {
        Write-Host 'Found Maven cached installation'
      }
# Note: env variables are not correctly updated by choco (setting it manually)
# Prepend Java entry, remove Ruby entry (C:\Ruby193\bin;) from PATH
  - cmd: SET PATH=C:\tools\apache-maven-3.6.0\bin;%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package -B -Dmaven.test.skip=true
test_script:
  - mvn test -B
cache:
  - C:\tools\apache-maven-3.6.0\
